### ISSUE TITLE
Usability Documentation

### ISSUE THREAD

**Issue by amandarichardsonn** [CrayLabs/SmartSim-Scaling#32]
## Description
There has been much work completed on the scaling studies with little update to documentation. We need to update the documentation for usability purposes. 

## Tasks
 - [ ] Add throughput colocated documentation - add name, synopsis, description, flags, examples & description of C++ file
 - [ ] Edit throughput standard documentation - add examples
 - [ ] Add data aggregation python documentation - add name, synopsis, description, flags, examples & description of C++ file
 - [ ] Add data aggregation file system documentation - add name, synopsis, description, flags, examples & description of C++ file
 - [ ] Update inference standard / colocated, throughput standard & data aggregation standard flags
 - [ ] Update Setup instructions to include module loads
 - [ ] Go though installation from scratch
