### ISSUE TITLE
Results and Process Results Documentation

### ISSUE THREAD

**Issue by amandarichardsonn** [CrayLabs/SmartSim-Scaling#36]
## Description
The plotter as well as the process results function has been revamped with no update to documentation. We need to update documentation for usability purposes. 

This task will be completed on Horizon.

## Tasks
- [ ] Update Process Results - Update flags, description and examples
- [ ] Add information for results organization - provide descriptions of files created during scaling study runs & location of files
- [ ] Add information for process results organization - provide descriptions of files created during process results & location of files
- [ ] Add information for the plotter - add flag, synopsis, description, flags and examples
- [ ] Update plotter images (examples for all scaling tests)
- [ ] Update KeyDB plotter examples (examples for all scaling tests)
